### ISSUE TITLE
Rotten Tomatoes - App Review

### ISSUE THREAD

**Issue by natoparkway** [natoparkway/CP_RottenTomatoes#1]
Please take a look and let me know what you think! /cc @codepathreview

Milestones I attempted but struggled with:
1) Having the search bar move as you scroll
2) Implementing a more nuanced off-screen scroll
3) Horizontal scrolling
4) Getting the keyboard to be dismissed wherever you click, but not having it affect functionality.

**Comment by codepathreview** [comment]
:+1: nice work. The point of this homework was to explore a simple example of a full MVC application with a RESTful API.
Detailed comments:
- Nice code styling. Check out these Swift style guides:
  - [Ray Wenderlich Swift Style Guide](https://github.com/raywenderlich/swift-style-guide)
  - [Github Swift Style Guide](https://github.com/github/swift-style-guide)
- Nice work implementing the Movie model.
- Your custom Movie cell should have a property called `movie`. In the custom setter of `movie`, you should configure the various labels and images. This decouples your custom cells from the table view controllers.
- Your images are loading synchronously. This will block the UI thread and make it so that your app appears frozen while the images are being downloaded.
- Nice work setting up the proper modes for the images so that they are not stretched.
- Nice work implementing the error message on network failure.

**Comment by natoparkway** [comment]
Thanks for the feedback!

What do you mean about decoupling the custom cells from the tableview
controllers?

Also, how would I load the images asynchronously? Does Swift support
threads?

Thanks!
